
var XGenPath=function(xGenPath,dotIsClass){this._position=0;this._steps=[];this._xGenPath=xGenPath;this._dotIsClass=typeof dotIsClass=='undefined'?true:dotIsClass;if(xGenPath){var steps=xGenPath.split("/");for(var step in steps){this._steps.push(new XGenPathStep(steps[step],this._dotIsClass));}}};XGenPath.prototype.getStep=function(){if(this._position>=this._steps.length){return null;}
return this._steps[this._position];};XGenPath.prototype.next=function(){var newPath=new XGenPath(null,this.dotIsClass);newPath._position=this._position+1;newPath._steps=this._steps;return newPath;};XGenPath.prototype.isTail=function(){return this._position==this._steps.length-1;};var XGenPathStep=function(step,dotIsClass){this.element;this.attributes=null;this.arrayLength=1;this.parse(step,dotIsClass);if(this.element===null||this.element===""){throw new Error("Element name missing in step");}};XGenPathStep.prototype.parse=function(step,dotIsClass){var stepPart=step;if(step.lastIndexOf("]")===step.length-1){var arraySize=stepPart.substring(stepPart.lastIndexOf('[')+1,stepPart.lastIndexOf(']'));try{this.arrayLength=parseInt(arraySize);}catch(err){throw new Error("Array index invalid parsing step "+step);}
stepPart=stepPart.substring(0,step.lastIndexOf('['));}
if(stepPart.lastIndexOf("}")===stepPart.length-1){this.attributes={};var attsString=stepPart.substring(stepPart.lastIndexOf('{')+1,stepPart.lastIndexOf('}'));stepPart=stepPart.substring(0,step.lastIndexOf('{'));var atts=attsString.split(",");for(var a=0;a<atts.length;a++){var nameVal=atts[a].split("=");try{this.attributes[nameVal[0]]=nameVal[1];}catch(err){throw new Error("Attribute syntax invalid parsing step "+step);}}}
if(stepPart.indexOf('#')>-1){if(this.attributes===null){this.attributes={};}
this.attributes.id=stepPart.substring(stepPart.indexOf('#')+1);stepPart=stepPart.substring(0,stepPart.indexOf('#'));}
if(dotIsClass&&stepPart.indexOf('.')>-1){if(this.attributes===null){this.attributes={};}
this.attributes.class=stepPart.substring(stepPart.indexOf('.')+1);stepPart=stepPart.substring(0,stepPart.indexOf('.'));}
this.element=stepPart;};XGenPathStep.prototype.getAttributes=function(){return this.attributes;};XGenPathStep.prototype.getElement=function(){return this.element;};XGenPathStep.prototype.getArrayLength=function(){return this.arrayLength;};jQuery.prototype.create=function(xGenPath){var tailNodes=[];var context;if(arguments.length===0){throw new Error("Missing xGenPath in create()");}
var parsedPath=new XGenPath(xGenPath,true);var context=this;if(parsedPath.length>1){context=[];for(var i=0;i<this.length;i++){context.push(document.createElement("div"));}}
this._createPath(context,parsedPath,tailNodes);if(parsedPath.length>1){for(var i=0;i<this.length;i++){var generated=context[i].childNodes;for(var e=0;e<generated.length;e++){this[i].appendChild(generated[e]);}}}
return jQuery(tailNodes);};jQuery.prototype._createPath=function(context,xGenPath,tailNodes){var step=xGenPath.getStep();if(step==null)return;for(var i=0;i<context.length;i++){var node=context[i];var generatedElements=this._createPathStep(node,step);this._createPath(generatedElements,xGenPath.next(),tailNodes);if(xGenPath.isTail()){for(var g=0;g<generatedElements.length;g++){tailNodes.push(generatedElements[g]);}}}};jQuery.prototype._createPathStep=function(node,step){var generatedNodes=[];for(var i=0;i<step.getArrayLength();i++){var element=document.createElement(step.getElement());node.appendChild(element);if(step.getAttributes()!=null){this._setAttributes(element,step.getAttributes());}
generatedNodes.push(element);}
return generatedNodes;};jQuery.prototype._setAttributes=function(elem,atts){for(var key in atts){elem.setAttribute(key,atts[key]);}};